FROM node:16-alpine

RUN mkdir -p /app

WORKDIR /app

EXPOSE 3000

COPY package*.json ./

RUN npm install

RUN ls -la

COPY . ./

RUN ls -la

RUN npm run build

RUN npm install -g serve

CMD [ "serve" ,"-s", "build"]